local theme = require("base46").current_theme
local base16 = require("base46").theme_tables[theme].base_16
local colors = require("base46").theme_tables[theme].base_30
local lighten = require("base46.colors").change_hex_lightness

local defaults = {
  Added = { fg = colors.green },
  Removed = { fg = colors.red },
  Changed = { fg = colors.yellow },
  MatchWord = { bg = colors.grey, fg = colors.white },
  Pmenu = { bg = colors.one_bg },
  PmenuSbar = { bg = colors.one_bg },
  PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
  PmenuThumb = { bg = colors.grey },
  MatchParen = { link = "MatchWord" },
  Comment = { fg = colors.light_grey },
  CursorLineNr = { fg = colors.white },
  LineNr = { fg = colors.grey },
  FloatBorder = { fg = colors.blue },
  FloatTitle = { fg = colors.white, bg = colors.grey },
  NormalFloat = { bg = colors.darker_black },
  NvimInternalError = { fg = colors.red },
  WinSeparator = { fg = colors.line },
  Normal = { fg = base16.base05, bg = base16.base00 },
  DevIconDefault = { fg = colors.red },
  Debug = { fg = base16.base08 },
  Directory = { fg = base16.base0D },
  Error = { fg = base16.base00, bg = base16.base08 },
  ErrorMsg = { fg = base16.base08, bg = base16.base00 },
  Exception = { fg = base16.base08 },
  FoldColumn = { fg = theme.base0F, bg = "none" },
  Folded = { fg = colors.light_grey, bg = colors.black2 },
  IncSearch = { fg = base16.base01, bg = base16.base09 },
  Macro = { fg = base16.base08 },
  ModeMsg = { fg = base16.base0B },
  MoreMsg = { fg = base16.base0B },
  Question = { fg = base16.base0D },
  Search = { fg = base16.base01, bg = base16.base0A },
  Substitute = { fg = base16.base01, bg = base16.base0A },
  SpecialKey = { fg = base16.base03 },
  TooLong = { fg = base16.base08 },
  Visual = { bg = base16.base02 },
  VisualNOS = { fg = base16.base08 },
  WarningMsg = { fg = base16.base08 },
  WildMenu = { fg = base16.base08, bg = base16.base0A },
  Title = { fg = base16.base0D },
  Conceal = { bg = "NONE" },
  Cursor = { fg = base16.base00, bg = base16.base05 },
  NonText = { fg = base16.base03 },
  SignColumn = { fg = base16.base03 },
  ColorColumn = { bg = colors.black2 },
  CursorColumn = { bg = base16.base01 },
  CursorLine = { bg = colors.black2 },
  QuickFixLine = { bg = base16.base01 },
  healthSuccess = { bg = colors.green, fg = colors.black },
  WinBar = { bg = "NONE" },
  WinBarNC = { bg = "NONE" },

  -- lazy.nvim
  LazyH1 = { bg = colors.green, fg = colors.black },
  LazyButton = { bg = colors.one_bg, fg = lighten(colors.light_grey, vim.o.bg == "dark" and 10 or -20) },
  LazyH2 = { fg = colors.red, bold = true, underline = true },
  LazyReasonPlugin = { fg = colors.red },
  LazyValue = { fg = colors.teal },
  LazyDir = { fg = base16.base05 },
  LazyUrl = { fg = base16.base05 },
  LazyCommit = { fg = colors.green },
  LazyNoCond = { fg = colors.red },
  LazySpecial = { fg = colors.blue },
  LazyReasonFt = { fg = colors.purple },
  LazyOperator = { fg = colors.white },
  LazyReasonKeys = { fg = colors.teal },
  LazyTaskOutput = { fg = colors.white },
  LazyCommitIssue = { fg = colors.pink },
  LazyReasonEvent = { fg = colors.yellow },
  LazyReasonStart = { fg = colors.white },
  LazyReasonRuntime = { fg = colors.nord_blue },
  LazyReasonCmd = { fg = colors.sun },
  LazyReasonSource = { fg = colors.cyan },
  LazyReasonImport = { fg = colors.white },
  LazyProgressDone = { fg = colors.green },

  NvDashAscii = { fg = colors.blue },
  NvDashButtons = { fg = colors.light_grey },
  NvDashFooter = { fg = colors.red },
}

-- merge statusline & hl_add tables!
return vim.tbl_deep_extend("force", defaults, require("base46").turn_str_to_color(require("base46").opts.hl_add or {}))
